# name: Connect EC2 and Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Add SSH key
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa

#       - name: Disable Host Key Checking
#         run: |
#           echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

#       - name: Connect to EC2 and Run Commands
#         run: |
#           ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
#             echo "Connected to EC2"
#             mkdir mansukh
#             cd mansukh
#             pwd
#             touch /home/ubuntu/mansukh/file1
#             echo "Deployment Finished!"
#           EOF



name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Disable Host Key Checking
        run: |
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Connect to EC2 and Deploy Code
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Connected to EC2"

            # SET YOUR PATH HERE
            PROJECT_DIR="/home/ubuntu/myapp"
            REPO_URL="https://github.com/harman275/connect-to-ec2.git"

            echo "Checking project folder..."

            # If project folder does NOT exist â†’ clone repo
            if [ ! -d "$PROJECT_DIR/.git" ]; then
              echo "Project not found. Cloning repository..."
              git clone $REPO_URL $PROJECT_DIR
            else
              echo "Project exists. Pulling latest code..."
              cd $PROJECT_DIR
              git pull origin main
            fi

            echo "Code updated successfully!"
            ls -la $PROJECT_DIR

            echo "Deployment Finished!"
          EOF
      - name: install apache2
        run: |
          sudo apt-get update
          sudo apt install apache2 -y
          sudo systemctl start apache2
