# name: Connect EC2 and Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Add SSH key
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa

#       - name: Disable Host Key Checking
#         run: |
#           echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

#       - name: Connect to EC2 and Run Commands
#         run: |
#           ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
#             echo "Connected to EC2"
#             mkdir mansukh
#             cd mansukh
#             pwd
#             touch /home/ubuntu/mansukh/file1
#             echo "Deployment Finished!"
#           EOF



name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Disable Host Key Checking
        run: |
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Connect to EC2 and Pull Latest Code
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

            echo "Connected to EC2"

            cd /home/ubuntu/mansukh   # <-- Set your project folder here

            echo "Pulling latest code..."
            git pull origin main     # <-- Pull latest code from GitHub

            echo "Code pulled successfully!"
            ls -la
    
            echo "Deployment Finished!"
          EOF
